### ISSUE TITLE
Incompatibility of Custom Frappe POS App with ERPNext v15?

### ISSUE THREAD

**Issue by edardev** [nestorbird/GETPOS#40]
Hi Team,

Request:
Could you please confirm if the GETPOS app is compatible with ERPNext version 15? If it is, could you provide guidance on resolving this installation issue?

Thank you!

I attempted to install the custom Frappe POS app (GETPOS) on ERPNext version 15, but the installation fails with the following error: 
2024-09-17 21:41:42 wait-for-it: waiting 120 seconds for db:3306
2024-09-17 21:41:42 wait-for-it: db:3306 is available after 0 seconds
2024-09-17 21:41:42 wait-for-it: waiting 120 seconds for redis-cache:6379
2024-09-17 21:41:42 wait-for-it: redis-cache:6379 is available after 0 seconds
2024-09-17 21:41:42 wait-for-it: waiting 120 seconds for redis-queue:6379
2024-09-17 21:41:42 wait-for-it: redis-queue:6379 is available after 0 seconds
2024-09-17 21:41:42 sites/common_site_config.json found
2024-09-17 21:41:44 Site frontend already exists
2024-09-17 21:41:46 App erpnext already installed
2024-09-17 21:41:46 App hrms already installed
2024-09-17 21:41:49 App payments already installed
2024-09-17 21:41:51 App crm already installed
2024-09-17 21:41:53 App builder already installed
2024-09-17 21:41:55 App insights already installed
2024-09-17 21:41:57 App ecommerce_integrations already installed
2024-09-17 21:41:58 App erpnext already installed
2024-09-17 21:41:59 App lending already installed
2024-09-17 21:42:00 App lms already installed
2024-09-17 21:42:02 App helpdesk already installed
2024-09-17 21:42:03 App print_designer already installed
2024-09-17 21:42:05 App gameplan already installed
2024-09-17 21:42:08 
2024-09-17 21:42:08 Installing nbpos...
2024-09-17 21:42:18 
Updating DocTypes for nbpos         : [====                                    ] 11%
Updating DocTypes for nbpos         : [========                                ] 22%
Updating DocTypes for nbpos         : [=============                           ] 33%
Updating DocTypes for nbpos         : [=================                       ] 44%
Updating DocTypes for nbpos         : [======================                  ] 55%
Updating DocTypes for nbpos         : [==========================              ] 66%
Updating DocTypes for nbpos         : [===============================         ] 77%
Updating DocTypes for nbpos         : [===================================     ] 88%
Updating DocTypes for nbpos         : [========================================] 100%
2024-09-17 21:42:18 Updating customizations for Item Group
2024-09-17 21:42:18 Updating customizations for Item
2024-09-17 21:42:18 An error occurred while installing nbpos: Item: Options must be a valid DocType for field HSN/SAC in row 8
2024-09-17 21:42:18 Traceback with variables (most recent call last):
2024-09-17 21:42:18   File "apps/frappe/frappe/commands/site.py", line 445, in install_app
2024-09-17 21:42:18     _install_app(app, verbose=context.verbose, force=force)
2024-09-17 21:42:18       context = {'sites': ['frontend'], 'force': False, 'verbose': False, 'profile': False}
2024-09-17 21:42:18       apps = ('nbpos',)
2024-09-17 21:42:18       force = False
2024-09-17 21:42:18       _install_app = <function install_app at 0x7f6f05617b00>
2024-09-17 21:42:18       filelock = <function filelock at 0x7f6f05615300>
2024-09-17 21:42:18       exit_code = 0
2024-09-17 21:42:18       site = 'frontend'
2024-09-17 21:42:18       app = 'nbpos'
2024-09-17 21:42:18       err = WrongOptionsDoctypeLinkError('Item: Options must be a valid DocType for field HSN/SAC in row 8')
2024-09-17 21:42:18   File "apps/frappe/frappe/installer.py", line 318, in install_app
2024-09-17 21:42:18     sync_customizations(name)
2024-09-17 21:42:18       name = 'nbpos'
2024-09-17 21:42:18       verbose = False
2024-09-17 21:42:18       set_as_patched = True
2024-09-17 21:42:18       force = False
2024-09-17 21:42:18       sync_jobs = <function sync_jobs at 0x7f6f04970720>
2024-09-17 21:42:18       sync_for = <function sync_for at 0x7f6f049716c0>
2024-09-17 21:42:18       sync_customizations = <function sync_customizations at 0x7f6f06140860>
2024-09-17 21:42:18       sync_fixtures = <function sync_fixtures at 0x7f6f049719e0>
2024-09-17 21:42:18       app_hooks = {'after_migrate': ['nbpos.nbpos.after_migrate.main'], 'app_color': ['grey'], 'app_description': ['nbpos'], 'app_email': ['swapnil.pawar'], 'app_icon': ['octicon octicon-file-directory'], 'app_include_js': ['/assets/nbpos/js/nbpos.js'], 'app_license': ['MIT'], 'app_name': ['nbpos'], 'app_publisher': ['swapnil'], 'app_title': ['nbpos'], 'app_version': ['0.0.1'], 'doc_events': {'Warehouse': {'validate': ['nbpos.nbpos.hooks.warehouse.validate_hub_manager']}, 'Customer': {'validate': ['nbpos.nbpos.hooks.customer.validate']}, 'Sales Order': {'on_submit': ['nbpos.nbpos.hooks.sales_order.on_submit'], 'validate': ['nbpos.nbpos.hooks.sales_order.validate']}, 'Sales Invoice': {'on_submit': ['nbpos.nbpos.hooks.sales_invoice.on_submit']}, 'Item Price': {'validate': ['nbpos.nbpos.hooks.item_price.validate_item_price']}}, 'doctype_js': {'Sales Order': ['public/js/doctype_js/sales_order.js'], 'Warehouse': ['public/js/doctype_js/warehouse.js'], 'Account': ['public/js/doctype_js/account.js'], 'Customer'...
2024-09-17 21:42:18       installed_apps = ['frappe', 'erpnext', 'hrms', 'payments', 'crm', 'builder', 'insights', 'ecommerce_integrations', 'lending', 'lms', 'helpdesk', 'print_designer', 'gameplan']
2024-09-17 21:42:18       fn = 'print_designer.install.after_app_install'
2024-09-17 21:42:18   File "apps/frappe/frappe/modules/utils.py", line 117, in sync_customizations
2024-09-17 21:42:18     sync_customizations_for_doctype(data, folder, fname)
2024-09-17 21:42:18       app = 'nbpos'
2024-09-17 21:42:18       apps = ['nbpos']
2024-09-17 21:42:18       app_name = 'nbpos'
2024-09-17 21:42:18       module_name = 'nbpos'
2024-09-17 21:42:18       folder = 'apps/nbpos/nbpos/nbpos/custom'
2024-09-17 21:42:18       fname = 'item.json'
2024-09-17 21:42:18       f = <_io.TextIOWrapper name='apps/nbpos/nbpos/nbpos/custom/item.json' mode='r' encoding='UTF-8'>
2024-09-17 21:42:18       data = {'custom_fields': [{'_assign': None, '_comments': None, '_liked_by': None, '_user_tags': None, 'allow_in_quick_entry': 0, 'allow_on_submit': 0, 'bold': 0, 'collapsible': 0, 'collapsible_depends_on': None, 'columns': 0, 'creation': '2021-10-13 16:00:17.621360', 'default': None, 'depends_on': None, 'description': None, 'docstatus': 0, 'dt': 'Item', 'fetch_from': None, 'fetch_if_empty': 0, 'fieldname': 'hub_sync_id', 'fieldtype': 'Data', 'hidden': 1, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'idx': 1, 'ignore_user_permissions': 0, 'ignore_xss_filter': 0, 'in_global_search': 0, 'in_list_view': 0, 'in_preview': 0, 'in_standard_filter': 0, 'insert_after': None, 'label': 'Hub Sync ID', 'length': 0, 'mandatory_depends_on': None, 'modified': '2021-10-13 16:00:17.621360', 'modified_by': 'Administrator', 'name': 'Item-hub_sync_id', 'no_copy': 1, 'non_negative': 0, 'options': None, 'owner': 'Administrator', 'parent': None, 'parentfield': None, 'parenttype': None, 'permlevel': 0, 'precis...
2024-09-17 21:42:18   File "apps/frappe/frappe/modules/utils.py", line 190, in sync_customizations_for_doctype
2024-09-17 21:42:18     validate_fields_for_doctype(doctype)
2024-09-17 21:42:18       data = {'custom_fields': [{'_assign': None, '_comments': None, '_liked_by': None, '_user_tags': None, 'allow_in_quick_entry': 0, 'allow_on_submit': 0, 'bold': 0, 'collapsible': 0, 'collapsible_depends_on': None, 'columns': 0, 'creation': '2021-10-13 16:00:17.621360', 'default': None, 'depends_on': None, 'description': None, 'docstatus': 0, 'dt': 'Item', 'fetch_from': None, 'fetch_if_empty': 0, 'fieldname': 'hub_sync_id', 'fieldtype': 'Data', 'hidden': 1, 'hide_border': 0, 'hide_days': 0, 'hide_seconds': 0, 'idx': 1, 'ignore_user_permissions': 0, 'ignore_xss_filter': 0, 'in_global_search': 0, 'in_list_view': 0, 'in_preview': 0, 'in_standard_filter': 0, 'insert_after': None, 'label': 'Hub Sync ID', 'length': 0, 'mandatory_depends_on': None, 'modified': '2021-10-13 16:00:17.621360', 'modified_by': 'Administrator', 'name': 'Item-hub_sync_id', 'no_copy': 1, 'non_negative': 0, 'options': None, 'owner': 'Administrator', 'parent': None, 'parentfield': None, 'parenttype': None, 'permlevel': 0, 'precis...
2024-09-17 21:42:18       folder = 'apps/nbpos/nbpos/nbpos/custom'
2024-09-17 21:42:18       filename = 'item.json'
2024-09-17 21:42:18       validate_fields_for_doctype = <function validate_fields_for_doctype at 0x7f6ef8493560>
2024-09-17 21:42:18       update_schema = True
2024-09-17 21:42:18       sync = <function sync_customizations_for_doctype.<locals>.sync at 0x7f6ee8831c60>
2024-09-17 21:42:18       doctype = 'Item'
2024-09-17 21:42:18   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1201, in validate_fields_for_doctype
2024-09-17 21:42:18     validate_fields(meta)
2024-09-17 21:42:18       doctype = 'Item'
2024-09-17 21:42:18       meta = <Meta: Item>
2024-09-17 21:42:18   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1649, in validate_fields
2024-09-17 21:42:18     check_link_table_options(meta.get("name"), d)
2024-09-17 21:42:18       meta = <Meta: Item>
2024-09-17 21:42:18       check_illegal_characters = <function validate_fields.<locals>.check_illegal_characters at 0x7f6ee8831120>
2024-09-17 21:42:18       check_invalid_fieldnames = <function validate_fields.<locals>.check_invalid_fieldnames at 0x7f6ee8831f80>
2024-09-17 21:42:18       check_unique_fieldname = <function validate_fields.<locals>.check_unique_fieldname at 0x7f6ee8832340>
2024-09-17 21:42:18       check_fieldname_length = <function validate_fields.<locals>.check_fieldname_length at 0x7f6ee8831ee0>
2024-09-17 21:42:18       check_illegal_mandatory = <function validate_fields.<locals>.check_illegal_mandatory at 0x7f6ee8832020>
2024-09-17 21:42:18       check_link_table_options = <function validate_fields.<locals>.check_link_table_options at 0x7f6ee8832160>
2024-09-17 21:42:18       check_hidden_and_mandatory = <function validate_fields.<locals>.check_hidden_and_mandatory at 0x7f6ee8831e40>
2024-09-17 21:42:18       check_width = <function validate_fields.<locals>.check_width at 0x7f6ee8832200>
2024-09-17 21:42:18       check_in_list_view = <function validate_fields.<locals>.check_in_list_view at 0x7f6ee88319e0>
2024-09-17 21:42:18       check_in_global_search = <function validate_fields.<locals>.check_in_global_search at 0x7f6ee8832520>
2024-09-17 21:42:18       check_dynamic_link_options = <function validate_fields.<locals>.check_dynamic_link_options at 0x7f6ee8831260>
2024-09-17 21:42:18       check_illegal_default = <function validate_fields.<locals>.check_illegal_default at 0x7f6ee8831b20>
2024-09-17 21:42:18       check_precision = <function validate_fields.<locals>.check_precision at 0x7f6ee88323e0>
2024-09-17 21:42:18       check_unique_and_text = <function validate_fields.<locals>.check_unique_and_text at 0x7f6ee8832660>
2024-09-17 21:42:18       check_fold = <function validate_fields.<locals>.check_fold at 0x7f6ee8832700>
2024-09-17 21:42:18       check_search_fields = <function validate_fields.<locals>.check_search_fields at 0x7f6ee88327a0>
2024-09-17 21:42:18       check_title_field = <function validate_fields.<locals>.check_title_field at 0x7f6ee8832840>
2024-09-17 21:42:18       check_image_field = <function validate_fields.<locals>.check_image_field at 0x7f6ee88328e0>
2024-09-17 21:42:18       check_is_published_field = <function validate_fields.<locals>.check_is_published_field at 0x7f6ee8832980>
2024-09-17 21:42:18       check_website_search_field = <function validate_fields.<locals>.check_website_search_field at 0x7f6ee8832a20>
2024-09-17 21:42:18       check_timeline_field = <function validate_fields.<locals>.check_timeline_field at 0x7f6ee8832ac0>
2024-09-17 21:42:18       check_sort_field = <function validate_fields.<locals>.check_sort_field at 0x7f6ee8832b60>
2024-09-17 21:42:18       check_illegal_depends_on_conditions = <function validate_fields.<locals>.check_illegal_depends_on_conditions at 0x7f6ee8832c00>
2024-09-17 21:42:18       check_table_multiselect_option = <function validate_fields.<locals>.check_table_multiselect_option at 0x7f6ee8832ca0>
2024-09-17 21:42:18       scrub_options_in_select = <function validate_fields.<locals>.scrub_options_in_select at 0x7f6ee8832d40>
2024-09-17 21:42:18       validate_fetch_from = <function validate_fields.<locals>.validate_fetch_from at 0x7f6ee8832de0>
2024-09-17 21:42:18       validate_data_field_type = <function validate_fields.<locals>.validate_data_field_type at 0x7f6ee8832e80>
2024-09-17 21:42:18       check_child_table_option = <function validate_fields.<locals>.check_child_table_option at 0x7f6ee8832f20>
2024-09-17 21:42:18       check_max_height = <function validate_fields.<locals>.check_max_height at 0x7f6ee8832fc0>
2024-09-17 21:42:18       check_no_of_ratings = <function validate_fields.<locals>.check_no_of_ratings at 0x7f6ee8833060>
2024-09-17 21:42:18       d = <LinkDocField: gst_hsn_code parent=Item>
2024-09-17 21:42:18       fieldname_list = ['hub_sync_id', 'details', 'naming_series', 'item_code', 'item_name', 'item_group', 'incldues_item_group', 'gst_hsn_code', 'is_nil_exempt', 'is_non_gst', 'stock_uom', 'column_break0', 'disabled', 'allow_alternative_item', 'is_stock_item', 'has_variants', 'opening_stock', 'valuation_rate', 'standard_rate', 'is_fixed_asset', 'auto_create_assets', 'is_grouped_asset', 'asset_category', 'asset_naming_series', 'over_delivery_receipt_allowance', 'over_billing_allowance', 'image', 'section_break_11', 'description', 'hub_manager_list', 'hub_managers', 'brand', 'unit_of_measure_conversion', 'uoms', 'dashboard_tab', 'inventory_section', 'inventory_settings_section', 'shelf_life_in_days', 'end_of_life', 'default_material_request_type', 'valuation_method', 'column_break1', 'warranty_period', 'weight_per_unit', 'weight_uom', 'allow_negative_stock', 'sb_barcodes', 'barcodes', 'reorder_section', 'reorder_levels', 'serial_nos_and_batches', 'has_batch_no', 'create_new_batch', 'batch_number_series', 'has...
2024-09-17 21:42:18       fields = [<DataDocField: hub_sync_id parent=Item>, <Tab BreakDocField: details parent=Item>, <SelectDocField: naming_series parent=Item>, <DataDocField: item_code parent=Item>, <DataDocField: item_name parent=Item>, <LinkDocField: item_group parent=Item>, <Table MultiSelectDocField: incldues_item_group parent=Item>, <LinkDocField: gst_hsn_code parent=Item>, <CheckDocField: is_nil_exempt parent=Item>, <CheckDocField: is_non_gst parent=Item>, <LinkDocField: stock_uom parent=Item>, <Column BreakDocField: column_break0 parent=Item>, <CheckDocField: disabled parent=Item>, <CheckDocField: allow_alternative_item parent=Item>, <CheckDocField: is_stock_item parent=Item>, <CheckDocField: has_variants parent=Item>, <FloatDocField: opening_stock parent=Item>, <CurrencyDocField: valuation_rate parent=Item>, <CurrencyDocField: standard_rate parent=Item>, <CheckDocField: is_fixed_asset parent=Item>, <CheckDocField: auto_create_assets parent=Item>, <CheckDocField: is_grouped_asset parent=Item>, <LinkDocField: ...
2024-09-17 21:42:18       not_allowed_in_list_view = ['Section Break', 'Column Break', 'Tab Break', 'HTML', 'Table', 'Table MultiSelect', 'Button', 'Image', 'Fold', 'Heading', 'Attach Image']
2024-09-17 21:42:18   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1276, in check_link_table_options
2024-09-17 21:42:18     frappe.throw(
2024-09-17 21:42:18       docname = 'Item'
2024-09-17 21:42:18       d = <LinkDocField: gst_hsn_code parent=Item>
2024-09-17 21:42:18       options = None
2024-09-17 21:42:18   File "apps/frappe/frappe/__init__.py", line 652, in throw
2024-09-17 21:42:18     msgprint(
2024-09-17 21:42:18       msg = 'Item: Options must be a valid DocType for field HSN/SAC in row 8'
2024-09-17 21:42:18       exc = <class 'frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError'>
2024-09-17 21:42:18       title = None
2024-09-17 21:42:18       is_minimizable = False
2024-09-17 21:42:18       wide = False
2024-09-17 21:42:18       as_list = False
2024-09-17 21:42:18       primary_action = None
2024-09-17 21:42:18   File "apps/frappe/frappe/__init__.py", line 617, in msgprint
2024-09-17 21:42:18     _raise_exception()
2024-09-17 21:42:18       msg = 'Item: Options must be a valid DocType for field HSN/SAC in row 8'
2024-09-17 21:42:18       title = None
2024-09-17 21:42:18       raise_exception = <class 'frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError'>
2024-09-17 21:42:18       as_table = False
2024-09-17 21:42:18       as_list = False
2024-09-17 21:42:18       indicator = 'red'
2024-09-17 21:42:18       alert = False
2024-09-17 21:42:18       primary_action = None
2024-09-17 21:42:18       is_minimizable = False
2024-09-17 21:42:18       wide = False
2024-09-17 21:42:18       realtime = False
2024-09-17 21:42:18       sys = <module 'sys' (built-in)>
2024-09-17 21:42:18       _raise_exception = <function msgprint.<locals>._raise_exception at 0x7f6ee8833240>
2024-09-17 21:42:18       inspect = <module 'inspect' from '/usr/local/lib/python3.11/inspect.py'>
2024-09-17 21:42:18       out = {'message': 'Item: Options must be a valid DocType for field HSN/SAC in row 8', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '3d7de8281bd5eacf2034d7e56b3be82735690a6f073439bac2a80669'}
2024-09-17 21:42:18   File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
2024-09-17 21:42:18     raise exc
2024-09-17 21:42:18       exc = WrongOptionsDoctypeLinkError('Item: Options must be a valid DocType for field HSN/SAC in row 8')
2024-09-17 21:42:18       inspect = <module 'inspect' from '/usr/local/lib/python3.11/inspect.py'>
2024-09-17 21:42:18       msg = 'Item: Options must be a valid DocType for field HSN/SAC in row 8'
2024-09-17 21:42:18       out = {'message': 'Item: Options must be a valid DocType for field HSN/SAC in row 8', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '3d7de8281bd5eacf2034d7e56b3be82735690a6f073439bac2a80669'}
2024-09-17 21:42:18       raise_exception = <class 'frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError'>
2024-09-17 21:42:18 frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError: Item: Options must be a valid DocType for field HSN/SAC in row 8

**Comment by ssinghnb** [comment]
@edardev We are working on a new release for Github and will share next week.

**Comment by Altrix-One** [comment]
HSN/SAC seems to be a dependency,the last time I had an issue like this I looked at what modules introduced this doctype. For my issue it was India Compliance that was missing (doctype that was part of it)

**Comment by kemboi22** [comment]
Has this issue been fixed since am trying to but it in a docker image but i get an error every time i build it 

```
 Running build command for getpos
#10 581.8 $ cd GetPOS && yarn build
#10 581.8 $ vite build --base=/assets/getpos/GetPOS/ && yarn copy-html-entry
#10 581.8 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#10 581.8 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#10 581.8 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#10 581.8 subprocess.CalledProcessError: Command 'bench build' returned non-zero exit status 1.
#10 581.8 
#10 581.8 The above exception was the direct cause of the following exception:
#10 581.8 
#10 581.8 Traceback (most recent call last):
#10 581.8   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 75, in init
#10 581.8     init(
#10 581.8   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
#10 581.8     return fn(*args, **kwargs)
#10 581.8            ^^^^^^^^^^^^^^^^^^^
#10 581.8   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", line 112, in init
#10 581.8     build_assets(bench_path=path)
#10 581.8   File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", line 380, in build_assets
#10 581.8     exec_cmd(command, cwd=bench_path, env=env)
#10 581.8   File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 178, in exec_cmd
#10 581.8     raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
#10 581.8 bench.exceptions.CommandFailedError: bench build
#10 581.8 
#10 581.8 ERROR: There was a problem while creating /home/frappe/frappe-bench
```

**Comment by edardev** [comment]
> HSN/SAC seems to be a dependency,the last time I had an issue like this I looked at what modules introduced this doctype. For my issue it was India Compliance that was missing (doctype that was part of it)

This potential solution makes a lot of sense to me. However, since I live in the USA, I’m unsure if the Indian Compliance module might conflict with other apps or modules.

**Comment by Altrix-One** [comment]
@edardev I am sure it will, this is a bare bone solution and not the full solution.I explored it and moved on. Seems like you need to pay to have the full package, not sure if anything changed.

**Comment by ssinghnb** [comment]
@kemboi22 let me look into it and respond back to you.
@edardev , India Compliance is not mandatory and it can run without it.

@Altrix-One , the new solution is a react based web app and has all the essential features as listed here https://frappecloud.com/marketplace/apps/nbpos 

For more features like return, Loyalty and gift card you can reach out to us.
