### ISSUE TITLE
Error when installing to an ERPNext 14 site

### ISSUE THREAD

**Issue by azwalzaman** [nestorbird/GETPOS#41]
I am installing it on an ERPNext site which has India_Compliance installed

```
Installing nbpos...
Updating DocTypes for nbpos         : [========================================] 100%
Updating customizations for Warehouse
Updating customizations for Sales Order
Updating customizations for Item
Updating customizations for Account
Updating customizations for Item Group
Updating customizations for Sales Invoice Item
Updating customizations for Packed Item
Updating customizations for Party Account
Updating customizations for Sales Invoice
An error occurred while installing nbpos: Default value for naming_series must be in the list of options.
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 400, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 312, in install_app
    sync_customizations(name)
  File "apps/frappe/frappe/modules/utils.py", line 114, in sync_customizations
    sync_customizations_for_doctype(data, folder, fname)
  File "apps/frappe/frappe/modules/utils.py", line 189, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1049, in validate_fields_for_doctype
    validate_fields(meta)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1494, in validate_fields
    check_illegal_default(d)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1198, in check_illegal_default
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 548, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 509, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 455, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Default value for naming_series must be in the list of options.
```

**Comment by ssinghnb** [comment]
@azwalzaman We have updated the code and it now has a react based application. to access it post installation, go to yoursite.frappecloud/getpos-react
